package main

// All money values are integer minor units (for IDR that is just whole rupiah).

type Trip struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	BaseCurrency string `json:"baseCurrency"`
	Info         string `json:"info,omitempty"`
	CreatedAt    string `json:"createdAt"`
}

type Person struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Color       string `json:"color,omitempty"`
	BankAccount string `json:"bankAccount,omitempty"` // payout details (bank / e-wallet)
}

// A receipt line. sharedBy = the people who split this line EVENLY.
type Item struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Quantity    int      `json:"quantity"`
	UnitPrice   int      `json:"unitPrice"`
	LineTotal   int      `json:"lineTotal"`
	SharedBy    []string `json:"sharedBy"`
	NeedsReview bool     `json:"needsReview,omitempty"`
	Note        string   `json:"note,omitempty"`
}

// An itemized restaurant/store bill.
type Receipt struct {
	ID         string `json:"id"`
	Title      string `json:"title"`
	Sub        string `json:"sub,omitempty"`
	Date       string `json:"date,omitempty"`
	Time       string `json:"time,omitempty"`
	PayerID    string `json:"payerId"`
	Items      []Item `json:"items"`
	GrandTotal int    `json:"grandTotal"` // 0 -> derive from line totals
	ImageRef   string `json:"imageRef,omitempty"`
}

// A flat shared trip cost (villa, petrol, tickets...). shares interpret per splitMode.
type Expense struct {
	ID        string         `json:"id"`
	Title     string         `json:"title"`
	Amount    int            `json:"amount"`
	PayerID   string         `json:"payerId"`
	SplitMode string         `json:"splitMode"` // EVENLY | BY_SHARES | BY_PERCENTAGE | BY_AMOUNT
	Shares    map[string]int `json:"shares"`    // personId -> weight/percent/amount (per splitMode)
	Note      string         `json:"note,omitempty"`
}

// Manual ledger entry. kind: "debt" (from owes to) | "payment" (from already paid to).
type Adjustment struct {
	ID     string `json:"id"`
	Kind   string `json:"kind"`
	FromID string `json:"fromId"`
	ToID   string `json:"toId"`
	Amount int    `json:"amount"`
	Label  string `json:"label,omitempty"`
}

// A point on the itinerary. LinkedExpenseID optionally ties a stop to a shared
// cost so the map can show what it cost and jump to the splitter.
type Stop struct {
	ID              string     `json:"id"`
	Name            string     `json:"name"`
	Type            string     `json:"type,omitempty"` // start|fuel|food|hotel|beach|viewpoint|...
	Badge           string     `json:"badge,omitempty"`
	Note            string     `json:"note,omitempty"`
	Lat             float64    `json:"lat"`
	Lng             float64    `json:"lng"`
	Time            string     `json:"time,omitempty"`
	URL             string     `json:"url,omitempty"`
	Rating          float64    `json:"rating,omitempty"`
	LinkedExpenseID string     `json:"linkedExpenseId,omitempty"`
	Done            bool       `json:"done,omitempty"`        // checked off during the trip (shared group state)
	Mode            string     `json:"mode,omitempty"`        // how you ARRIVE here: car|scooter|taxi|public|bike|walk|boat|flight
	DurationMin     int        `json:"durationMin,omitempty"` // planned visit length, minutes
	Cost            int        `json:"cost,omitempty"`        // estimated cost, minor units (planning only; actuals live in Bills)
	Links           *StopLinks `json:"links,omitempty"`       // typed source links
}

// StopLinks holds the typed source links the planner/AI can attach to a stop.
type StopLinks struct {
	Maps    string `json:"maps,omitempty"`
	Booking string `json:"booking,omitempty"`
	Tickets string `json:"tickets,omitempty"`
	Site    string `json:"site,omitempty"`
}

type Day struct {
	ID        string `json:"id"`
	Label     string `json:"label,omitempty"`     // "Day 1"
	DateLabel string `json:"dateLabel,omitempty"` // "Sat 13 Jun"
	Title     string `json:"title,omitempty"`     // "Tuban → Bedugul"
	Stops     []Stop `json:"stops"`
}

// Optional per-trip itinerary (map route). Generated by AI and/or hand-edited.
type Itinerary struct {
	Title string `json:"title,omitempty"`
	Days  []Day  `json:"days"`
}

// A planned payment in a published settlement. Status: pending → submitted → verified.
type Transfer struct {
	ID        string `json:"id"`
	FromID    string `json:"fromId"`
	ToID      string `json:"toId"`
	Amount    int    `json:"amount"`
	Status    string `json:"status"`             // pending | submitted | verified
	ProofRef  string `json:"proofRef,omitempty"` // stored proof image filename
	UpdatedAt string `json:"updatedAt,omitempty"`
}

// A frozen "who pays whom" plan (Plan A). Published once, then payments are tracked
// against it without reshuffling. Recomputed only on an explicit re-generate.
type Settlement struct {
	Published   bool       `json:"published"`
	GeneratedAt string     `json:"generatedAt,omitempty"`
	Transfers   []Transfer `json:"transfers"`
}

// Trip-wide planning preferences. Drives the AI generator and the budget UI.
// DailyTarget and HomeCurrency are SENSITIVE (money) — never exposed on the public page.
type Profile struct {
	StartDate    string   `json:"startDate,omitempty"`   // ISO yyyy-mm-dd
	Pace         string   `json:"pace,omitempty"`        // relaxed|balanced|packed
	BudgetLevel  string   `json:"budgetLevel,omitempty"` // shoestring|mid|comfort|lux
	DailyTarget  int      `json:"dailyTarget,omitempty"` // minor units (whole IDR); SENSITIVE
	Interests    []string `json:"interests,omitempty"`
	Dietary      []string `json:"dietary,omitempty"` // e.g. halal, veg, vegan
	Adults       int      `json:"adults,omitempty"`
	Kids         int      `json:"kids,omitempty"`
	Mobility     string   `json:"mobility,omitempty"`     // easy|moderate|active
	HomeCurrency string   `json:"homeCurrency,omitempty"` // SENSITIVE
	Capacity     int      `json:"capacity,omitempty"`     // max travelers; 0 = no cap
}

// A public RSVP on the join wall: a name + party size, recorded on the public page.
// Names + counts only — never money. Moderated (removable) by the organizer.
type Signup struct {
	Name  string `json:"name"`
	Count int    `json:"count,omitempty"`
	At    string `json:"at,omitempty"`
}

// The whole trip document — one JSON file per trip.
type TripDoc struct {
	Trip        Trip         `json:"trip"`
	People      []Person     `json:"people"`
	Receipts    []Receipt    `json:"receipts"`
	Expenses    []Expense    `json:"expenses"`
	Adjustments []Adjustment `json:"adjustments"`
	Itinerary   *Itinerary   `json:"itinerary,omitempty"`
	Profile     *Profile     `json:"profile,omitempty"`
	Settlement  *Settlement  `json:"settlement,omitempty"`
	Signups     []Signup     `json:"signups,omitempty"`
	Rev         int          `json:"rev"`
	UpdatedAt   string       `json:"updatedAt"`
}

// Cheap summary for the trip list.
type TripSummary struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	BaseCurrency string `json:"baseCurrency"`
	CreatedAt    string `json:"createdAt"`
	People       int    `json:"people"`
	Receipts     int    `json:"receipts"`
	Expenses     int    `json:"expenses"`
}

func (d *TripDoc) summary() TripSummary {
	return TripSummary{
		ID: d.Trip.ID, Name: d.Trip.Name, BaseCurrency: d.Trip.BaseCurrency,
		CreatedAt: d.Trip.CreatedAt, People: len(d.People),
		Receipts: len(d.Receipts), Expenses: len(d.Expenses),
	}
}

func (d *TripDoc) normalize() {
	if d.People == nil {
		d.People = []Person{}
	}
	if d.Receipts == nil {
		d.Receipts = []Receipt{}
	}
	if d.Expenses == nil {
		d.Expenses = []Expense{}
	}
	if d.Adjustments == nil {
		d.Adjustments = []Adjustment{}
	}
	for i := range d.Receipts {
		if d.Receipts[i].Items == nil {
			d.Receipts[i].Items = []Item{}
		}
		for j := range d.Receipts[i].Items {
			if d.Receipts[i].Items[j].SharedBy == nil {
				d.Receipts[i].Items[j].SharedBy = []string{}
			}
		}
	}
	for i := range d.Expenses {
		if d.Expenses[i].Shares == nil {
			d.Expenses[i].Shares = map[string]int{}
		}
		if d.Expenses[i].SplitMode == "" {
			d.Expenses[i].SplitMode = "EVENLY"
		}
	}
}
